// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package P2P

type Status = int32
const (
	StatusOK Status = 0
	StatusNG Status = 1
)

var EnumNamesStatus = map[Status]string{
	StatusOK:"OK",
	StatusNG:"NG",
}

